
LanguageName = "中文"
contentDir = "content/zh"
languageDirection = 'ltr'
languageCode = 'zh-cn'
title = "理想派"
weight = 1
copyright = "理想派 | [湘ICP备2024043073号](https://beian.miit.gov.cn/)  @2024"

[params]
  dateFormat = "2006-01-02"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"